import React, { useEffect, useState, useCallback } from 'react'
import { Link } from 'react-router-dom'
import { Scale, Calculator, Book, TrendingUp, Plus, ArrowRight, Calendar } from 'lucide-react'
import { User } from '@supabase/supabase-js'
import { format, addDays } from 'date-fns'
import { fi } from 'date-fns/locale'

import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from '@/components/ui/card'
import { supabase } from '@/integrations/supabase/client'
import MeshBackground from '@/components/MeshBackground'
import SEO from '@/components/SEO'
import AdBanner from '@/components/AdBanner'

interface DashboardProps {
    user: User
}

interface Dog {
    id: string
    name: string
    age_years?: number | null
}

interface WeightEntry {
    id: string
    weight: number
    date: string
    created_at: string
}

const Dashboard: React.FC<DashboardProps> = ({ user }) => {
    const [dogs, setDogs] = useState<Dog[]>([])
    const [lastWeight, setLastWeight] = useState<WeightEntry | null>(null)
    const [loading, setLoading] = useState(true)

    const fetchUserData = useCallback(async () => {
        try {
            setLoading(true)

            // Fetch dogs
            const { data: dogsData } = await supabase
                .from('dogs')
                .select('*')
                .eq('user_id', user.id)

            // Cast to unknown then Dog[] to avoid strict type mismatches with autogenerated types
            setDogs((dogsData as unknown as Dog[]) || [])

            if (dogsData && dogsData.length > 0) {
                // Fetch latest weight for the first dog
                const { data: weightData } = await supabase
                    .from('weight_entries')
                    .select('*')
                    .eq('dog_id', dogsData[0].id)
                    .order('date', { ascending: false })
                    .limit(1)

                if (weightData && weightData.length > 0) {
                    setLastWeight(weightData[0] as unknown as WeightEntry)
                }
            }
        } catch (error) {
            console.error('Error fetching dashboard data:', error)
        } finally {
            setLoading(false)
        }
    }, [user])

    useEffect(() => {
        fetchUserData()
    }, [fetchUserData])

    const getGreeting = () => {
        const hour = new Date().getHours()
        if (hour < 10) return 'Hyvää huomenta'
        if (hour < 18) return 'Hyvää päivää'
        return 'Hyvää iltaa'
    }

    // Calculate next weigh-in (e.g., 1 week after last)
    const getNextWeighIn = () => {
        if (!lastWeight) return 'Tänään'
        const lastDate = lastWeight.date || lastWeight.created_at;
        const nextDate = addDays(new Date(lastDate), 7)
        if (new Date() > nextDate) return 'Tänään'
        return format(nextDate, 'd.M.', { locale: fi })
    }

    return (
        <div className="min-h-screen flex flex-col pb-20">
            <SEO
                title="Oma Pentulaskuri - Dashboard"
                description="Hallintapaneeli pennun kasvun seurantaan."
            />

            <MeshBackground variant="dashboard" />

            <main className="container px-4 pt-24 md:pt-32 pb-12 mx-auto relative z-10">
                <header className="mb-10">
                    <h1 className="text-3xl md:text-4xl font-serif font-bold text-stone-900">
                        {getGreeting()}, {user.email?.split('@')[0]}!
                        <span className="inline-block animate-wave ml-2 origin-bottom-right">👋</span>
                    </h1>
                    {dogs.length > 0 ? (
                        <p className="text-stone-600 mt-2 text-lg">
                            Tässä on pennun {dogs[0].name} tilannekatsaus.
                        </p>
                    ) : (
                        <p className="text-stone-600 mt-2 text-lg">
                            Aloita lisäämällä pentusi tiedot.
                        </p>
                    )}
                </header>

                {loading ? (
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-6 animate-pulse">
                        {[1, 2, 3].map(i => (
                            <div key={i} className="h-48 bg-stone-200 rounded-xl"></div>
                        ))}
                    </div>
                ) : (
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">

                        {/* Quick Summary / Weight */}
                        <Card className="border-0 shadow-md bg-white/60 backdrop-blur-sm hover:bg-white/80 transition-all group">
                            <CardHeader className="flex flex-row items-center justify-between pb-2">
                                <CardTitle className="text-lg font-medium text-stone-700">Viimeisin paino</CardTitle>
                                <Scale className="w-5 h-5 text-terracotta-500" />
                            </CardHeader>
                            <CardContent>
                                {lastWeight ? (
                                    <div className="space-y-1">
                                        <p className="text-3xl font-bold text-stone-900">{lastWeight.weight} kg</p>
                                        <p className="text-sm text-stone-500">
                                            Mitattu {format(new Date(lastWeight.date || lastWeight.created_at), 'd.M.yyyy')}
                                        </p>
                                    </div>
                                ) : (
                                    <div className="py-2">
                                        <p className="text-stone-500 mb-2">Ei mittauksia vielä</p>
                                        <Button variant="outline" size="sm" asChild>
                                            <Link to="/weight-tracker">Lisää ensimmäinen</Link>
                                        </Button>
                                    </div>
                                )}
                            </CardContent>
                            {lastWeight && (
                                <CardFooter>
                                    <Button variant="ghost" className="w-full justify-between text-terracotta-600 hover:text-terracotta-700 p-0 hover:bg-transparent" asChild>
                                        <Link to="/weight-tracker">
                                            Lisää uusi mittaus <Plus className="w-4 h-4" />
                                        </Link>
                                    </Button>
                                </CardFooter>
                            )}
                        </Card>

                        {/* Reminder / Next Steps */}
                        <Card className="border-0 shadow-md bg-white/60 backdrop-blur-sm hover:bg-white/80 transition-all">
                            <CardHeader className="flex flex-row items-center justify-between pb-2">
                                <CardTitle className="text-lg font-medium text-stone-700">Seuraava punnitus</CardTitle>
                                <Calendar className="w-5 h-5 text-blue-500" />
                            </CardHeader>
                            <CardContent>
                                <div className="space-y-1">
                                    <p className="text-3xl font-bold text-stone-900">{getNextWeighIn()}</p>
                                    <p className="text-sm text-stone-500">Suositeltu viikoittainen seuranta</p>
                                </div>
                            </CardContent>
                            <CardFooter>
                                <Button variant="ghost" className="w-full justify-between text-blue-600 hover:text-blue-700 p-0 hover:bg-transparent" asChild>
                                    <Link to="/weight-tracker">
                                        Avaa seuranta <ArrowRight className="w-4 h-4 ml-1" />
                                    </Link>
                                </Button>
                            </CardFooter>
                        </Card>

                        {/* Quick Actions / Apps */}
                        <Card className="border-0 shadow-md bg-gradient-to-br from-terracotta-50 to-orange-50 md:col-span-2 lg:col-span-1">
                            <CardHeader>
                                <CardTitle className="text-lg font-medium text-stone-700">Pikalinkit</CardTitle>
                            </CardHeader>
                            <CardContent className="grid grid-cols-2 gap-3">
                                <Link to="/calculator" className="flex flex-col items-center justify-center p-4 bg-white rounded-lg shadow-sm hover:shadow-md transition-all gap-2 text-center group">
                                    <Calculator className="w-6 h-6 text-terracotta-500 group-hover:scale-110 transition-transform" />
                                    <span className="text-sm font-medium text-stone-700">Ruoka-laskuri</span>
                                </Link>
                                <Link to="/puppy-book" className="flex flex-col items-center justify-center p-4 bg-white rounded-lg shadow-sm hover:shadow-md transition-all gap-2 text-center group">
                                    <Book className="w-6 h-6 text-purple-500 group-hover:scale-110 transition-transform" />
                                    <span className="text-sm font-medium text-stone-700">Pentukirja</span>
                                </Link>
                                <Link to="/guides" className="flex flex-col items-center justify-center p-4 bg-white rounded-lg shadow-sm hover:shadow-md transition-all gap-2 text-center group">
                                    <Book className="w-6 h-6 text-green-500 group-hover:scale-110 transition-transform" />
                                    <span className="text-sm font-medium text-stone-700">Oppaat</span>
                                </Link>
                                <Link to="/settings" className="flex flex-col items-center justify-center p-4 bg-white rounded-lg shadow-sm hover:shadow-md transition-all gap-2 text-center group">
                                    <TrendingUp className="w-6 h-6 text-blue-500 group-hover:scale-110 transition-transform" />
                                    <span className="text-sm font-medium text-stone-700">Asetukset</span>
                                </Link>
                            </CardContent>
                        </Card>

                        {/* Ad Banner - Visible as 4th card */}
                        <div className="md:col-span-2 lg:col-span-1 flex justify-center">
                            <AdBanner variant="rectangle" className="w-full max-w-sm h-full" />
                        </div>

                    </div>
                )}
            </main>
        </div>
    )
}

export default Dashboard
