name: CI Quality Gate - Disabled

# Temporarily disabled to enable Vercel deployment
# Re-enable after deployment pipeline is working

on:
  workflow_dispatch: # Manual trigger only

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: echo "CI temporarily disabled for deployment testing"
