name: Deploy to IONOS - Disabled

# Disabled - switching to Vercel deployment
# IONOS deployment replaced with Vercel automatic deployment

on:
  workflow_dispatch: # Manual trigger only
    inputs:
      environment:
        description: 'Environment to deploy to (DISABLED - using Vercel)'
        required: true
        default: production
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment Disabled
        run: |
          echo "IONOS deployment disabled - using Vercel automatic deployment"
          echo "Vercel will automatically deploy from GitHub repository"
          echo "Check Vercel dashboard for deployment status"
