name: Deploy to IONOS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    environment:
      name: production
      url: https://pentulaskuri.com
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci --legacy-peer-deps
    
    - name: Run linting
      run: npm run lint
      continue-on-error: true  # Don't fail deployment on lint warnings
    
    - name: Build project
      run: npm run build
      env:
        NODE_ENV: production
    
    - name: Verify build artifacts
      run: |
        echo "Verifying build output..."
        ls -la dist/
        if [ ! -f "dist/index.html" ]; then
          echo "❌ index.html not found in dist/"
          exit 1
        fi
        if [ ! -d "dist/assets" ]; then
          echo "❌ assets directory not found in dist/"
          exit 1
        fi
        echo "✅ Build artifacts verified"
    
    - name: Run tests
      run: npm run test:mobile
    
    - name: Deploy to IONOS via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.IONOS_FTP_HOST }}
        username: ${{ secrets.IONOS_FTP_USERNAME }}
        password: ${{ secrets.IONOS_FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir: /
        state-name: ionos-deploy-state
        dry-run: false
        log-level: verbose
        dangerous-clean-slate: false
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.env*
    
    - name: Verify deployment
      run: |
        echo "Deployment completed successfully!"
        echo "Site URL: https://pentulaskuri.com"
        
        # Wait for deployment to propagate
        sleep 30
        
        # Check health endpoint first
        echo "Testing health endpoint..."
        curl -f https://pentulaskuri.com/health || echo "Health endpoint not accessible"
        
        # Check main site
        echo "Testing main site..."
        response=$(curl -s -o /dev/null -w "%{http_code}" https://pentulaskuri.com)
        if [ "$response" != "200" ]; then
          echo "❌ Main site returned HTTP $response"
          exit 1
        fi
        
        # Check if main site returns HTML content
        content=$(curl -s https://pentulaskuri.com)
        if [[ "$content" == *"Koiranpennun Painonseuranta"* ]]; then
          echo "✅ Site is serving correct content"
        else
          echo "❌ Site content verification failed"
          echo "Received content length: ${#content}"
          exit 1
        fi
    
    - name: Send deployment notification
      if: always()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        channel: '#deployments'
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}
        text: |
          Deployment to IONOS: ${{ job.status }}
          Branch: ${{ github.ref }}
          Commit: ${{ github.sha }}
          Author: ${{ github.actor }}
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      continue-on-error: true